# Generated by Django 3.1b1 on 2020-12-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20201201_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de la reserva'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
