# Generated by Django 3.1b1 on 2020-12-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20201201_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposolicitante',
            options={'verbose_name': 'Tipo Solicitante', 'verbose_name_plural': 'Tipos de Solicitante'},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de la reserva'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento de la reserva'),
        ),
        migrations.AlterField(
            model_name='tiposolicitante',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tiposolicitante',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
