# Generated by Django 3.1b1 on 2020-12-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20201201_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='barrio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
