# Generated by Django 3.1b1 on 2020-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20201201_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='adjuntocedula',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cedula/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='adjuntorut',
            field=models.FileField(blank=True, null=True, upload_to='uploads/rut/% Y/% m/% d/'),
        ),
    ]
