# Generated by Django 3.1b1 on 2020-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20201201_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
