# Generated by Django 3.1b1 on 2020-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cedula',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
