# Generated by Django 3.1.6 on 2021-02-14 17:46

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_solicitud_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='escenariodeportivo',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to=principal.models.nameFile),
        ),
        migrations.AddField(
            model_name='escenariodeportivo',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=principal.models.nameFile),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='adjuntocedula',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cedula/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='adjuntorut',
            field=models.FileField(blank=True, null=True, upload_to='uploads/rut/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
